import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema1 extends i0.VersionedSchema {
  Schema1({required super.database}) : super(version: 1);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    inAppMessageSeenDates,
    inAppMessageInteractions,
  ];
  late final Shape0 inAppMessageSeenDates = Shape0(
      source: i0.VersionedTable(
        entityName: 'in_app_message_seen_dates',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 inAppMessageInteractions = Shape1(
      source: i0.VersionedTable(
        entityName: 'in_app_message_interactions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_3,
          _column_4,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get message =>
      columnsByName['message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get seen =>
      columnsByName['seen']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('message', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_2(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('seen', aliasedName, false,
        type: i1.DriftSqlType.dateTime);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get message =>
      columnsByName['message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get interactions =>
      columnsByName['interactions']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('message', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'));
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('interactions', aliasedName, false,
        type: i1.DriftSqlType.string);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema1 schema) from0To1,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 0:
        final schema = Schema1(database: database);
        final migrator = i1.Migrator(database, schema);
        await from0To1(migrator, schema);
        return 1;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema1 schema) from0To1,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from0To1: from0To1,
    ));
