name: in_app_messaging
description: "Simple In-App Messaging for your application"
version: 0.0.6
repository: https://github.com/rIIh/in_app_messaging

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # utility
  version: ^3.0.0
  async: ^2.11.0
  freezed_annotation: ^2.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # tests
  test: ^1.25.2
  checks: ^0.3.0

  # codegen
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  freezed: ^2.5.2

  # linting
  flutter_lints: ^3.0.0

flutter:
