name: in_app_messaging
resolution: workspace
description: "Simple In-App Messaging for your application"
version: 0.0.20
repository: https://github.com/rIIh/in_app_messaging

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # framework
  in_app_messaging_json_logic: ^2.2.0

  # utility
  version: ^3.0.0
  async: ^2.11.0
  logging: ^1.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # tests
  test: ^1.25.2
  checks: ^0.3.0

  # codegen
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  freezed: ^3.0.0

  # linting
  flutter_lints: ^6.0.0

