name: sandbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # in app messaging
  in_app_messaging: 
  in_app_messaging_drift: 

  # other
  drift: 2.18.0
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^2.0.0
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.0
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
