name: sandbox
resolution: workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # in app messaging
  in_app_messaging: 
  in_app_messaging_drift: 

  # other
  drift: ^2.23.1
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^2.0.0
  riverpod_annotation: ^3.0.0-dev.16
  flutter_riverpod: ^3.0.0-dev.16
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.2.0
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^3.0.0-dev.16

flutter:
  uses-material-design: true
