name: in_app_messaging_drift
description: In-App Messaging persistence layer with Drift
version: 0.0.20
repository: https://github.com/rIIh/in_app_messaging

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  # framework
  in_app_messaging: ^0.0.17

  # utility
  path_provider: ^2.1.3
  drift: ^2.23.1
  path: ^1.9.0

dev_dependencies:
  # lints
  lints: ^3.0.0

  # codegen
  build_runner: ^2.4.11
  drift_dev: ^2.23.1
